version: '3.2'
services:

  db:
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=transactions
#  dashboard:
#    container_name: dashboard
#    image: dashboard:latest
#    env_file:
#      - dashboard.env
#    links:
#      - "db"
