# Generated by Django 3.2.4 on 2021-06-22 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_transactions_index'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transactions',
            old_name='name',
            new_name='senatorName',
        ),
        migrations.AlterField(
            model_name='transactions',
            name='index',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
